services:
  db:
    image: mariadb:12.3.2
    restart: on-failure
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: erp-refatorado
    command:
      - --character-set-server=utf8mb3
      - --collation-server=utf8mb3_general_ci
    volumes:
      - ./legado:/docker-entrypoind-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 20s
      timeout: 10s
      start_period: 10s
      retries: 5

  dbgate:
    image: dbgate/dbgate:7.3.1
    ports:
      - "8080:3000"
    depends_on:
      db:
        condition: service_healthy
