services:
  db:
    image: mariadb:12.3.2
    restart: on-failure
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: erp-refatorado
    command:
      - --character-set-server=utf8mb3
      - --collation-server=utf8mb3_general_ci
    volumes:
      - ./legado:/docker-entrypoind-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 20s
      timeout: 10s
      start_period: 10s
      retries: 5

  db_pg:
    image: postgres:16.0-alpine3.18
    restart: on-failure
    environment:
      POSTGRES_DB: erp-refatorado
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  dbgate:
    image: dbgate/dbgate:7.3.1
    ports:
      - "8080:3000"
    depends_on:
      db:
        condition: service_healthy
      db_pg:
        condition: service_healthy
